name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: dChancellor/scp-action@master
        env:
          HOST: ${{ secrets.LIGHTSAIL_HOST }}
          USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
          PORT: ${{ secrets.LIGHTSAIL_PORT }}
          KEY: ${{ secrets.LIGHTSAIL_SSHKEY }}
        with:
          source: './server'
          target: '~/dev/sudoku-solver'

      - name: Executing remote command
        uses: dChancellor/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
          PORT: ${{ secrets.LIGHTSAIL_PORT }}
          KEY: ${{ secrets.LIGHTSAIL_SSHKEY }}
          script: ls
